Feature/semantic exercise
OscarBosigas/html-tutorial pull request #3
Opened 2020-04-22 18:35 UTC by OscarBosigas

2020-04-22 21:06 UTC, juancho11gm commented on 3-semantic-html/semantic.html
> +
Please remove all the empty lines of your file

2020-04-22 21:10 UTC, juancho11gm requested changes
You have the structure of the HTML. Now you have to fill the elements with content. For example, you can use the `<li>` tags in the `<nav`> with items that you want to mention on the web page. The same with all the other elements that are empty.

2020-04-23 15:31 UTC, pushdev-code requested changes
Please include texts inside the tags, and remove the empty `<content>` tags

2020-04-23 15:31 UTC, pushdev-code commented on 3-semantic-html/semantic.html
> +                <h1></h1>
Please include some text so it's not just empty.

2020-04-23 15:31 UTC, pushdev-code commented on 3-semantic-html/semantic.html
> +                <content></content>
```suggestion
```
The content should be inside `<p></p>` from line 23

2020-04-23 19:35 UTC, merged